packages:
  - client/
  - server/
  - e2e/
allowBuilds:
  core-js: true
  bcrypt: true
  esbuild: true
  sqlite3: true
  negaposi-analyzer-ja: true
overrides:
  gifler>bluebird: 3.7.2
  gifler>omggif: 1.0.10
saveExact: true
shellEmulator: true
